version: '3'
services:
  sistemavotacao.api:
    image: ${DOCKER_REGISTRY-}sistemavotacao
    build:
      context: .
      dockerfile: src/SistemaVotacao.Api/Dockerfile
    depends_on:
        - database
  database:
    container_name: database
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql